{{- define "practice.labels" }}
  labels:
    generator: "helm"
    date: {{ now | htmlDate }}
{{- end }}
{{- if $.Values.enabled  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "practice.labels"  }}  
data:
  name: {{ .Values.name | repeat 5 }}
  drink: {{ .Values.favourite.drink | default "tea" | quote | upper }}
  location: {{ .Values.favourite.location | lower }}
  fruits: |-
  {{- range .Values.fruits }}
   - {{ . }}
  {{- end }}
  favfruits: |-
  {{- range $index,$fruit := .Values.fruits }}
   - {{ $index }} : {{ $fruit }}
  {{- end }}
  details: |-
  {{- range $key,$value := .Values.favourite }}
   - {{ $key }} : {{ $value }} 
  {{- end }}
  address: |-
  {{- with .Values.address }}
     state: {{ .state }}
     country: {{ .country }} 
  {{- end }}
{{- include "practice.companies" . | indent 2 }}
  {{- $files := .Files }}  
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }} : |-
     {{ $files.Get . }}
  {{- end }}
  filepaths: |-
  {{- range $path,$_ := .Files.Glob "**.toml" }}
   - {{ $.Files.Get $path }}
  {{- end }}
{{ (.Files.Glob "foo/*").AsConfig | indent 2 }}
  sample.txt: {{ range .Files.Lines "foo/sample.txt" }}
    {{ . }}{{ end }}
  salad: {{ .Values.global.salad }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret 
data:
{{ (.Files.Glob "bar/*").AsSecrets | indent 2 }}
  token: |-
  {{- range $path,$_ := .Files.Glob "bar/**.txt" }}
    {{ $.Files.Get $path | b64enc }}
  {{- end }}
